//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEVENTO
    {
        public int id_evento { get; set; }
        public string nom_evento { get; set; }
        public string lugar { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string descripcion { get; set; }
        public string foto_evento { get; set; }
        public int ID_user { get; set; }
    
        public virtual TBLUSER TBLUSER { get; set; }
    }
}
